name: 02 - Workflow Events

on:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "The workflow was triggered by a jhon-027@LAPTOP-T0EHUSSQ:~/gh-actions_course/.github/workflows event"
