name: 08 - Using Variables.

on: 
  push:
  workflow_dispatch:
    
env:
  MY_WORKFLOW_VAR: 'I am a workflow env var' 
  MY_OVERWRITTEN_VAR: 'I will be overwritten'       

jobs: 
  echo:
    runs-on: ubuntu-latest
    env: 
      MY_JOB_VAR: 'I am a job env var'
      MY_OVERWRITTEN_VAR: 'I have been overwritten at the job level' 
    steps: 
    - name: Print Env Variables
      env:
        STEP_VAR: 'I am a step env var'
        step_var2: 'I am another step var'
      run: |
        echo "Step env var: ${{ env.STEP_VAR }}"
        echo "Step env var 2: ${{ env.step_var2 }}"
        echo "Job env var: ${{ env.MY_JOB_VAR }}"    
        echo "Workflow env var: ${{ env.MY_WORKFLOW_VAR }}"
        echo "Overwritten: ${{ env.MY_OVERWRITTEN_VAR }}"  
      
    - name: Overwrite Job Variable
      env:
        MY_OVERWRITTEN_VAR: 'I have been overwritten at the step level' 
      run: |
        echo "Step env var: ${{ env.MY_OVERWRITTEN_VAR }}"    