name: 11 - Working with inputs

on: 
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "Skip deployment and only print build output"
        default: false

      target:
        type: string  # Corrected from environment to string
        required: true
        description: "Which environment the workflow will target"
        
      tag: 
        type: string  # Corrected from choice to string
        description: "Release from which to build and deploy"
        default: v3
        # Options management will be done within the run logic
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Build
        run: echo "Building from tag ${{ inputs.tag }}"

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.dry-run == 'false' }}  # Ensure dry-run condition is handled correctly
    environment: ${{ inputs.target }}  
    steps: 
      - name: Deploy 
        run: echo "Deploying to ${{ inputs.target }}" 
