name: 14 - working with artifacts

on:
  workflow_dispatch:

env:
  build-artifact-key: app-${{ github.sha }}    
  test-coverage-key: test-coverage-${{ github.sha }}

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
          path: ./14-artifacts/react-app/node_modules

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --coverage

      - name: Build code
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./14-artifacts/react-app/build
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.test-coverage-key }}   
          path: 14-artifacts/react-app/coverage    
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./build

      - name: Show folder structure
        run: ls -R 