name: 17 - 1 - Custom Actions - Composite

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        description: Environment to deploy to
        required: true
        default: dev
        options:
          - dev
          - prod

run-name: 17 - 1 - Custom Actions - Composite | env - ${{ github.event.inputs.target-env }}

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: '20.x'
          working-dir: ${{ env.working-directory }}
          target-env: ${{ github.event.inputs.target-env }}
    
      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
